name: Automatically release from head.

on:
  workflow_call:

jobs:
  Release-From-HEAD:
    name: Automatic release from 'HEAD'
    runs-on: ubuntu-latest

    # Only allow one action to run at a time.
    concurrency: release-from-head

    # Don't run on the upstream repository and only run on the right branch.
    if: ${{ (github.repository != 'The-OpenROAD-Project/OpenROAD') && endsWith(github.ref, '/sync') }}

    steps:

    - uses: actions/checkout@v3
      with:
       ref: master
       fetch-depth: 0

    - name: Generate TAG
      run: |
        # Create a tag of form v0.0-183-gdf2b162
        TAG="${TAG:-$(git describe --match=v*)}"
        TAG_EXISTS="$(git tag -l $TAG)"
        if [[ -z "$TAG_EXISTS" ]]; then
          echo "Generated TAG: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV
        else
          echo "Existing TAG: $TAG_EXISTS"
          echo "TAG_EXISTS=$TAG_EXISTS" >> $GITHUB_ENV          
        fi
        
    - name: Apply and push TAG
      if: ${{ env.TAG_EXISTS == '' }}
      run: |
        git config --local user.name "$BOT_USER"
        git config --local user.email "$BOT_EMAIL"
        git tag "$TAG"
        git push origin "HEAD:refs/tags/$TAG"
